# -*- coding: utf-8 -*-
"""PHANI_A00086573_CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sq8WLpvRFcEIdBIRkC3bmbZjIgMuYqzD
"""

!pip install -q kagglehub kagglehub[pandas-datasets] pandas

import os
import glob
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter

def list_all_files(folder_path):
    all_files = []
    for root, dirs, files in os.walk(folder_path):
        for f in files:
            all_files.append(os.path.join(root, f))
    return sorted(all_files)

def find_tabular_files(folder_path):
    patterns = ["**/*.csv", "**/*.xlsx", "**/*.xls", "**/*.json", "**/*.parquet"]
    files = []
    for p in patterns:
        files.extend(glob.glob(os.path.join(folder_path, p), recursive=True))
    return sorted(files)

def load_file_auto(file_path):
    ext = os.path.splitext(file_path)[1].lower()

    if ext == ".csv":
        try:
            return pd.read_csv(file_path)
        except:
            try:
                return pd.read_csv(file_path, encoding="utf-8-sig")
            except:
                return pd.read_csv(file_path, encoding="latin1")

    elif ext in [".xlsx", ".xls"]:
        return pd.read_excel(file_path)

    elif ext == ".json":
        return pd.read_json(file_path)

    elif ext == ".parquet":
        return pd.read_parquet(file_path)

    else:
        raise ValueError(f"Unsupported file type: {ext}")

def download_and_inspect(dataset_name, dataset_label):
    print("=" * 80)
    print(f"DOWNLOADING: {dataset_label}")
    print(f"Kaggle dataset: {dataset_name}")

    path = kagglehub.dataset_download(dataset_name)
    print("\nLocal path:")
    print(path)

    print("\nAll files found:")
    all_files = list_all_files(path)
    for f in all_files:
        print(f)

    tabular_files = find_tabular_files(path)
    print("\nTabular files found:")
    for i, f in enumerate(tabular_files):
        print(f"[{i}] {f}")

    if len(tabular_files) == 0:
        print("\nNo CSV/Excel/JSON/Parquet file found.")
        return path, None, None

    selected_file = tabular_files[0]
    print(f"\nLoading first detected tabular file:\n{selected_file}")

    df = load_file_auto(selected_file)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns.tolist())

    print("\nFirst 5 rows:")
    display(df.head())

    return path, selected_file, df

english_path, english_file, df_english = download_and_inspect(
    "clmentbisaillon/fake-and-real-news-dataset",
    "English Fake and Real News Dataset"
)

english_tabular_files = find_tabular_files(english_path)
print(english_tabular_files)

df_en_1 = load_file_auto(english_tabular_files[0])
df_en_2 = load_file_auto(english_tabular_files[1])

print("File 1 shape:", df_en_1.shape)
print("File 2 shape:", df_en_2.shape)

display(df_en_1.head())
display(df_en_2.head())

# Load both English files
df_en_1 = load_file_auto(english_tabular_files[0])   # File 1 = fake
df_en_2 = load_file_auto(english_tabular_files[1])   # File 2 = true

# Add labels manually as you confirmed
df_en_1["label"] = "fake"
df_en_2["label"] = "true"

# Add language column
df_en_1["language"] = "english"
df_en_2["language"] = "english"

# Combine both
df_english = pd.concat([df_en_1, df_en_2], ignore_index=True)

# Reset index
df_english.reset_index(drop=True, inplace=True)

# Check result
print("Combined English dataset shape:", df_english.shape)
print("\nLabel distribution:")
print(df_english["label"].value_counts())

display(df_english.head())

bengali_path, bengali_file, df_bengali = download_and_inspect(
    "musfiqurtuhin/bengali-fake-news-detection-dataset",
    "Bengali Fake News Detection Dataset"
)

# Keep and rename required columns
df_bengali = df_bengali[["headline", "content", "label"]].copy()
df_bengali = df_bengali.rename(columns={
    "headline": "title",
    "content": "text"
})

# Relabel label column
df_bengali["label"] = df_bengali["label"].replace({
    1: "true",
    0: "fake"
})

# Add language column
df_bengali["language"] = "bengali"

# Reorder columns
df_bengali = df_bengali[["language", "title", "text", "label"]]

print("Bengali dataset shape:", df_bengali.shape)
print("\nLabel distribution:")
print(df_bengali["label"].value_counts())

display(df_bengali.head())

hindi_path, hindi_file, df_hindi = download_and_inspect(
    "arnavagrawal22/arnsin-dl-cleaned1",
    "Hindi Dataset"
)

# Keep only required columns
df_hindi = df_hindi[["text", "label"]].copy()

# Relabel label column
# 1 = Fake News, 0 = True News
df_hindi["label"] = df_hindi["label"].replace({
    1: "fake",
    0: "true"
})

# Add language column
df_hindi["language"] = "hindi"

# Optional: create empty title column so structure matches other datasets
df_hindi["title"] = ""

# Reorder columns
df_hindi = df_hindi[["language", "title", "text", "label"]]

# Check result
print("Hindi dataset shape:", df_hindi.shape)
print("\nLabel distribution:")
print(df_hindi["label"].value_counts())

display(df_hindi.head())

# Keep only required columns from English
df_english = df_english[["language", "title", "text", "label"]].copy()

# Make sure labels are consistent
df_english["label"] = df_english["label"].replace({
    "fake": "fake",
    "true": "true"
})

print("English shape:", df_english.shape)
print(df_english["label"].value_counts())
display(df_english.head())

# Bengali exact structure
df_bengali = df_bengali[["language", "title", "text", "label"]].copy()
df_bengali["label"] = df_bengali["label"].replace({
    "fake": "fake",
    "true": "true"
})

print("Bengali shape:", df_bengali.shape)
print(df_bengali["label"].value_counts())
display(df_bengali.head())


# Hindi exact structure
df_hindi = df_hindi[["language", "title", "text", "label"]].copy()
df_hindi["label"] = df_hindi["label"].replace({
    "fake": "fake",
    "true": "true"
})

print("Hindi shape:", df_hindi.shape)
print(df_hindi["label"].value_counts())
display(df_hindi.head())

# Combine all datasets
df_combined = pd.concat(
    [df_english, df_bengali, df_hindi],
    ignore_index=True
)

print("Combined shape before cleaning:", df_combined.shape)
display(df_combined.head())

# Remove rows with missing text
df_combined = df_combined.dropna(subset=["text"])

# Convert title/text to string
df_combined["title"] = df_combined["title"].fillna("").astype(str)
df_combined["text"] = df_combined["text"].astype(str)

# Remove rows where text is empty after stripping spaces
df_combined = df_combined[df_combined["text"].str.strip() != ""]

# Drop duplicates based on title + text + label + language
df_combined = df_combined.drop_duplicates(
    subset=["language", "title", "text", "label"]
).reset_index(drop=True)

print("Combined shape after cleaning:", df_combined.shape)

print("Final columns:")
print(df_combined.columns.tolist())

print("\nLanguage distribution:")
print(df_combined["language"].value_counts())

print("\nLabel distribution:")
print(df_combined["label"].value_counts())

print("\nCross-tab: language vs label")
print(pd.crosstab(df_combined["language"], df_combined["label"]))

display(df_combined.head())

df_combined["full_text"] = (df_combined["title"] + " " + df_combined["text"]).str.strip()
df_combined["word_count"] = df_combined["full_text"].apply(lambda x: len(str(x).split()))
df_combined["char_count"] = df_combined["full_text"].apply(lambda x: len(str(x)))

"""1) Language distribution"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))
sns.countplot(data=df_combined, x="language", order=df_combined["language"].value_counts().index)
plt.title("Distribution of News Articles by Language", fontsize=14)
plt.xlabel("Language")
plt.ylabel("Number of Articles")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

plt.figure(figsize=(8,5))
sns.countplot(data=df_combined, x="language", hue="label", order=df_combined["language"].value_counts().index)
plt.title("Fake vs True News Distribution Across Languages", fontsize=14)
plt.xlabel("Language")
plt.ylabel("Number of Articles")
plt.legend(title="Label")
plt.tight_layout()
plt.show()

"""3) Text length distribution by language using word count"""

plt.figure(figsize=(9,5))
sns.boxplot(data=df_combined[df_combined["word_count"] <= 1000], x="language", y="word_count")
plt.title("Word Count Distribution by Language (Trimmed)", fontsize=14)
plt.xlabel("Language")
plt.ylabel("Word Count")
plt.tight_layout()
plt.show()

"""4) Top frequent words by language"""

from collections import Counter
import re

def get_top_words(text_series, n=10):
    words = " ".join(text_series.astype(str)).lower()
    words = re.findall(r"\w+", words)
    common_words = Counter(words).most_common(n)
    return pd.DataFrame(common_words, columns=["word", "count"])

languages = df_combined["language"].unique()

for lang in languages:
    temp_df = df_combined[df_combined["language"] == lang]
    top_words_df = get_top_words(temp_df["full_text"], n=10)

    plt.figure(figsize=(8,5))
    sns.barplot(data=top_words_df, x="count", y="word")
    plt.title(f"Top 10 Most Frequent Words in {lang.capitalize()} News", fontsize=14)
    plt.xlabel("Frequency")
    plt.ylabel("Word")
    plt.tight_layout()
    plt.show()

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

# Create final input text
df_combined["full_text"] = (
    df_combined["title"].fillna("").astype(str) + " " +
    df_combined["text"].fillna("").astype(str)
).str.strip()

# Label encoding
df_combined["label_num"] = df_combined["label"].map({
    "true": 0,
    "fake": 1
})

# Keep only useful columns
df_model = df_combined[["language", "full_text", "label", "label_num"]].copy()

# Remove missing
df_model = df_model.dropna(subset=["full_text", "label_num"]).reset_index(drop=True)

print("Final modelling dataset shape:", df_model.shape)
print(df_model["label"].value_counts())
print(df_model["language"].value_counts())

display(df_model.head())

# First split: train and temp
train_df, temp_df = train_test_split(
    df_model,
    test_size=0.30,
    random_state=42,
    stratify=df_model["label_num"]
)

# Second split: validation and test
val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    random_state=222,
    stratify=temp_df["label_num"]
)

print("Train shape:", train_df.shape)
print("Validation shape:", val_df.shape)
print("Test shape:", test_df.shape)

print("\nTrain label distribution:")
print(train_df["label"].value_counts(normalize=True))

print("\nValidation label distribution:")
print(val_df["label"].value_counts(normalize=True))

print("\nTest label distribution:")
print(test_df["label"].value_counts(normalize=True))

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_recall_fscore_support, classification_report, confusion_matrix

# Baseline pipeline
baseline_model = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=20000, ngram_range=(1,2))),
    ("clf", LogisticRegression(max_iter=200))
])

# Train
baseline_model.fit(train_df["full_text"], train_df["label_num"])

# Validation predictions
val_preds_baseline = baseline_model.predict(val_df["full_text"])

# Metrics
val_acc = accuracy_score(val_df["label_num"], val_preds_baseline)
val_prec, val_rec, val_f1, _ = precision_recall_fscore_support(
    val_df["label_num"], val_preds_baseline, average="binary"
)

print("Baseline Validation Accuracy:", round(val_acc, 4))
print("Baseline Validation Precision:", round(val_prec, 4))
print("Baseline Validation Recall:", round(val_rec, 4))
print("Baseline Validation F1:", round(val_f1, 4))

print("\nClassification Report:")
print(classification_report(val_df["label_num"], val_preds_baseline, target_names=["true", "fake"]))

import matplotlib.pyplot as plt
import seaborn as sns

cm = confusion_matrix(val_df["label_num"], val_preds_baseline)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["true", "fake"],
            yticklabels=["true", "fake"],
            linewidths=1, linecolor="black")
plt.title("Baseline Model Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.tight_layout()
plt.show()

!pip install -q transformers datasets accelerate evaluate sentencepiece gradio

from datasets import Dataset, DatasetDict

train_hf = Dataset.from_pandas(train_df[["full_text", "label_num"]].reset_index(drop=True))
val_hf = Dataset.from_pandas(val_df[["full_text", "label_num"]].reset_index(drop=True))
test_hf = Dataset.from_pandas(test_df[["full_text", "label_num"]].reset_index(drop=True))

dataset_dict = DatasetDict({
    "train": train_hf,
    "validation": val_hf,
    "test": test_hf
})

print(dataset_dict)

"""9. Common metric function"""

import evaluate
import numpy as np

accuracy_metric = evaluate.load("accuracy")
precision_metric = evaluate.load("precision")
recall_metric = evaluate.load("recall")
f1_metric = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    acc = accuracy_metric.compute(predictions=preds, references=labels)
    prec = precision_metric.compute(predictions=preds, references=labels, average="binary")
    rec = recall_metric.compute(predictions=preds, references=labels, average="binary")
    f1 = f1_metric.compute(predictions=preds, references=labels, average="binary")

    return {
        "accuracy": acc["accuracy"],
        "precision": prec["precision"],
        "recall": rec["recall"],
        "f1": f1["f1"]
    }

"""10. Model 1: mBERT"""

from transformers import AutoTokenizer

mbert_model_name = "bert-base-multilingual-cased"
mbert_tokenizer = AutoTokenizer.from_pretrained(mbert_model_name)

def tokenize_mbert(batch):
    return mbert_tokenizer(
        batch["full_text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

mbert_tokenized = dataset_dict.map(tokenize_mbert, batched=True)
mbert_tokenized = mbert_tokenized.rename_column("label_num", "labels")
mbert_tokenized.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

print(mbert_tokenized)

from transformers import AutoModelForSequenceClassification

mbert_model = AutoModelForSequenceClassification.from_pretrained(
    mbert_model_name,
    num_labels=2
)

from transformers import DataCollatorWithPadding

mbert_data_collator = DataCollatorWithPadding(tokenizer=mbert_tokenizer)

from transformers import TrainingArguments, Trainer

mbert_training_args = TrainingArguments(
    output_dir="./mbert_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    report_to="none",
    fp16=True
)

mbert_trainer = Trainer(
    model=mbert_model,
    args=mbert_training_args,
    train_dataset=mbert_tokenized["train"],
    eval_dataset=mbert_tokenized["validation"],
    processing_class=mbert_tokenizer,
    data_collator=mbert_data_collator,
    compute_metrics=compute_metrics
)

mbert_trainer.train()

mbert_val_results = mbert_trainer.evaluate(mbert_tokenized["validation"])
print("mBERT Validation Results:")
print(mbert_val_results)

"""11. mBERT test evaluation"""

mbert_test_results = mbert_trainer.evaluate(mbert_tokenized["test"])
print("mBERT Test Results:")
print(mbert_test_results)

mbert_test_pred = mbert_trainer.predict(mbert_tokenized["test"])
mbert_test_preds = np.argmax(mbert_test_pred.predictions, axis=1)
mbert_test_labels = np.array(test_df["label_num"])

print(classification_report(mbert_test_labels, mbert_test_preds, target_names=["true", "fake"]))

cm_mbert = confusion_matrix(mbert_test_labels, mbert_test_preds)

plt.figure(figsize=(5,4))
sns.heatmap(cm_mbert, annot=True, fmt="d", cmap="Blues",
            xticklabels=["true", "fake"],
            yticklabels=["true", "fake"],
            linewidths=1, linecolor="black")
plt.title("mBERT Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.tight_layout()
plt.show()

"""# 12. Model 2: XLM-RoBERTa"""

from transformers import AutoTokenizer

xlmr_model_name = "xlm-roberta-base"
xlmr_tokenizer = AutoTokenizer.from_pretrained(xlmr_model_name)

def tokenize_xlmr(batch):
    return xlmr_tokenizer(
        batch["full_text"],
        truncation=True,
        max_length=128
    )
xlmr_tokenized = dataset_dict.map(tokenize_xlmr, batched=True)
xlmr_tokenized = xlmr_tokenized.rename_column("label_num", "labels")
xlmr_tokenized.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

print(xlmr_tokenized)

from transformers import DataCollatorWithPadding

xlmr_data_collator = DataCollatorWithPadding(tokenizer=xlmr_tokenizer)

from transformers import AutoModelForSequenceClassification

xlmr_model = AutoModelForSequenceClassification.from_pretrained(
    xlmr_model_name,
    num_labels=2
)

from transformers import TrainingArguments, Trainer

xlmr_training_args = TrainingArguments(
    output_dir="./xlmr_results",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    report_to="none",
    fp16=True
)

xlmr_trainer = Trainer(
    model=xlmr_model,
    args=xlmr_training_args,
    train_dataset=xlmr_tokenized["train"],
    eval_dataset=xlmr_tokenized["validation"],
    data_collator=xlmr_data_collator,
    compute_metrics=compute_metrics
)

xlmr_trainer.train()

xlmr_val_results = xlmr_trainer.evaluate(xlmr_tokenized["validation"])
print("XLM-R Validation Results:")
print(xlmr_val_results)

xlmr_test_results = xlmr_trainer.evaluate(xlmr_tokenized["test"])
print("XLM-R Test Results:")
print(xlmr_test_results)

xlmr_test_pred = xlmr_trainer.predict(xlmr_tokenized["test"])
xlmr_test_preds = np.argmax(xlmr_test_pred.predictions, axis=1)
xlmr_test_labels = np.array(test_df["label_num"])

print(classification_report(xlmr_test_labels, xlmr_test_preds, target_names=["true", "fake"]))

cm_xlmr = confusion_matrix(xlmr_test_labels, xlmr_test_preds)

plt.figure(figsize=(5,4))
sns.heatmap(cm_xlmr, annot=True, fmt="d", cmap="Blues",
            xticklabels=["true", "fake"],
            yticklabels=["true", "fake"],
            linewidths=1, linecolor="black")
plt.title("XLM-RoBERTa Confusion Matrix")
plt.xlabel("Predicted Label")
plt.ylabel("Actual Label")
plt.tight_layout()
plt.show()

"""# Compare all models"""

comparison_df = pd.DataFrame([
    {
        "Model": "Baseline TF-IDF + Logistic Regression",
        "Accuracy": round(mbert_val_results.get("eval_accuracy", np.nan), 4) if False else round(val_acc, 4),
        "Precision": round(val_prec, 4),
        "Recall": round(val_rec, 4),
        "F1": round(val_f1, 4)
    },
    {
        "Model": "mBERT",
        "Accuracy": round(mbert_test_results["eval_accuracy"], 4),
        "Precision": round(mbert_test_results["eval_precision"], 4),
        "Recall": round(mbert_test_results["eval_recall"], 4),
        "F1": round(mbert_test_results["eval_f1"], 4)
    },
    {
        "Model": "XLM-RoBERTa",
        "Accuracy": round(xlmr_test_results["eval_accuracy"], 4),
        "Precision": round(xlmr_test_results["eval_precision"], 4),
        "Recall": round(xlmr_test_results["eval_recall"], 4),
        "F1": round(xlmr_test_results["eval_f1"], 4)
    }
])

display(comparison_df)

plt.figure(figsize=(8,5))
sns.barplot(data=comparison_df, x="Model", y="F1")
plt.title("Model Comparison Using F1-score")
plt.xlabel("Model")
plt.ylabel("F1-score")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

"""# Language-wise test analysis"""

test_results_df = test_df.copy().reset_index(drop=True)

test_results_df["mbert_pred"] = mbert_test_preds
test_results_df["xlmr_pred"] = xlmr_test_preds

print("mBERT language-wise performance")
for lang in test_results_df["language"].unique():
    temp = test_results_df[test_results_df["language"] == lang]
    acc = accuracy_score(temp["label_num"], temp["mbert_pred"])
    print(f"{lang}: {round(acc,4)}")

print("XLM-R language-wise performance")
for lang in test_results_df["language"].unique():
    temp = test_results_df[test_results_df["language"] == lang]
    acc = accuracy_score(temp["label_num"], temp["xlmr_pred"])
    print(f"{lang}: {round(acc,4)}")

"""# Predict on new custom samples

mBERT prediction function
"""

import torch
import torch.nn.functional as F

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
mbert_model.to(device)
xlmr_model.to(device)

def predict_news_mbert(text):
    inputs = mbert_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    ).to(device)

    with torch.no_grad():
        outputs = mbert_model(**inputs)
        probs = F.softmax(outputs.logits, dim=1)
        pred = torch.argmax(probs, dim=1).item()
        confidence = probs[0][pred].item()

    label_map = {0: "true", 1: "fake"}
    return label_map[pred], confidence

sample_text = "Breaking news: the government has officially announced a new national policy today."
pred_label, pred_conf = predict_news_mbert(sample_text)

print("mBERT Prediction:", pred_label)
print("Confidence:", round(pred_conf, 4))

"""XLM-R prediction function"""

def predict_news_xlmr(text):
    inputs = xlmr_tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=256
    ).to(device)

    with torch.no_grad():
        outputs = xlmr_model(**inputs)
        probs = F.softmax(outputs.logits, dim=1)
        pred = torch.argmax(probs, dim=1).item()
        confidence = probs[0][pred].item()

    label_map = {0: "true", 1: "fake"}
    return label_map[pred], confidence

sample_text_hi = "यह खबर पूरी तरह से झूठी है और सोशल मीडिया पर तेजी से फैल रही है।"
pred_label, pred_conf = predict_news_xlmr(sample_text_hi)

print("XLM-R Prediction:", pred_label)
print("Confidence:", round(pred_conf, 4))

"""# Show some real test predictions"""

sample_test_rows = test_df[["language", "full_text", "label"]].head(10).reset_index(drop=True)

preds = []
confs = []

for txt in sample_test_rows["full_text"]:
    label_pred, conf_pred = predict_news_xlmr(txt)
    preds.append(label_pred)
    confs.append(round(conf_pred, 4))

sample_test_rows["predicted_label"] = preds
sample_test_rows["confidence"] = confs

display(sample_test_rows)

"""# Save best model"""

import torch

# make sure eval mode
xlmr_model.eval()

# save smaller half-precision weights
state_dict_fp16 = {k: v.half() for k, v in xlmr_model.state_dict().items()}
torch.save(state_dict_fp16, "xlmr_fake_news_fp16.pth")

print("Saved smaller file: xlmr_fake_news_fp16.pth")